version: '2'
services:
  web:
    build: .
    image: lordtrosky
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - migration
      - db
      - redis
      - node_server
  db:
    image: postgres:10.2
    volumes:
      - .:/tmp/data/
  redis:
    image: redis:3.2.11
  migration:
    image: lordtrosky
    command: bash -c "python manage.py check; python manage.py migrate --noinput"
    volumes:
      - .:/code
  node_server:
    image: lordtrosky
    command: sh run.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/code

