# Generated by Django 2.2.9 on 2020-01-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_question_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_checking',
            field=models.BooleanField(default=True),
        ),
    ]
